### ISSUE TITLE
Feed the files to be searched from stdin

### ISSUE THREAD

**Issue by NightMachinary** [dainiusjocas/lucene-grep#107]
When there are a lot of files, using the argument list won’t work because of OS limits.

PS: Any way to cache the indices?

**Comment by dainiusjocas** [comment]
Lmgrep supports two ways to provide multiple files:
1. Explicit list of files when invoking lmgrep,
2. A GLOB pattern of filenames.

When using the (1) approach you can hit OS limits. However, in the (2) you pass just one parameter to the program (avoiding the OS limitations), and your huge list of files is handled inside the lmgrep.

And for the index caching, lmgrep has no such option now because it was designed to have all data in memory and when the process terminates no garbage is left on disk. However, it would not be too complicated to implement persisting indices (the regular Lucene way) and then lmgrep would search in those pre-computed indices.
