### ISSUE TITLE
Linux build doesn't run due to GLIBC error

### ISSUE THREAD

**Issue by SevereOverfl0w** [dainiusjocas/lucene-grep#23]
```
❯ lmgrep foo
lmgrep: /usr/lib/libc.so.6: version `GLIBC_2.32' not found (required by lmgrep)
```

Not sure what's going on!

**Comment by dainiusjocas** [comment]
Most likely is because you need a statically linked binary on your Linux box. Is it Alpne Linux that you're running @SevereOverfl0w ?

**Comment by SevereOverfl0w** [comment]
I'm not, I'm running a glibc-based distro (void linux).  The version of glibc available is 2.30 though, as they've not yet updated to the latest version.

**Comment by dainiusjocas** [comment]
@SevereOverfl0w try a new release https://github.com/dainiusjocas/lucene-grep/releases/tag/v2021.01.17 and let me know how it goes.

**Comment by SevereOverfl0w** [comment]
That starts up great, thanks!

**Comment by SevereOverfl0w** [comment]
```
❯ lmgrep foo
lmgrep: dl-call-libc-early-init.c:37: _dl_call_libc_early_init: Assertion `sym != NULL' failed.
zsh: abort      lmgrep foo
```

Spoke too soon!

**Comment by dainiusjocas** [comment]
Amazing, I've tested the static binary in the distroless static container and it worked.

@SevereOverfl0w does babashka or similar projects work on your machine? Because if they work I'll just copy their settings.

**Comment by SevereOverfl0w** [comment]
Void Linux has now switched to GLIBC 2.32 so it's now working for me.  Babashka does work on my machine, and historically always has, yeah.

**Comment by dainiusjocas** [comment]
> Void Linux has now switched to GLIBC 2.32 so it's now working for me.  Babashka does work on my machine, and historically always has, yeah.  

Once again, amazing. Thanks for letting me know!

**Comment by dainiusjocas** [comment]
I've reproduced the problem. The story goes like this: I've compiled the binary on Ubuntu 20.10 host in the Docker container that is `ghcr.io/graalvm/graalvm-ce:java11-21.0.0` (the official GraalVM docker). And the binary throws exactly the errors as mentioned in the comments when ran on CentOS 7.

Also, the same issue happens when building directly on Ubuntu 20.10.

The solution is to use another Docker `findepi/graalvm:java11-native` container.
