### ISSUE TITLE
[Q] Web frontend?

### ISSUE THREAD

**Issue by NightMachinary** [dainiusjocas/lucene-grep#98]
I wonder if you know any projects that have a ready-made web frontend to do full-text search on some files on disk. I want this to be able to search my notes on mobile.

**Comment by dainiusjocas** [comment]
I'm not aware of such projects. I guess that is mostly because such software is a security hole.

However, if you feel adventurous then you can write a simple HTTP server that would call `lmgrep` and search the filesystem. Similar to the example [here](https://github.com/dainiusjocas/lucene-grep/blob/main/examples/ruby-percolator/ruby-percolator.rb).
